site_name: 'Elementos de Sistemas'
theme:
  name: active-handout-theme

docs_dir: 'docs-src'
site_url: https://insper.github.io/Z01.1/
edit_uri: 'edit/docs/docs-src/'
repo_name: 'Insper/Z01.1'
repo_url: 'https://github.com/insper/Z01.1'
copyright: 'Copyright &copy; Rafael Corsi @ insper'

google_analytics:
  - UA-G-XQ38NZ62XF
  - auto

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - active-handout:
      telemetry: true
      backend_url: https://devlife-api.insper-comp.com.br/
      course_slug: 23b-ele
  - glightbox
  - termynal

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


nav:
- Home: 'index.md'

- 'Informações Gerais':
  - 'Home/Sobre-Criterios-de-Avaliacao.md'
  - 'Home/Sobre-Rubricas.md'
  - 'Home/Util-Aulas.md'
  - 'Home/Avaliacoes.md'

- 'Projetos':
  - 'Projetos/A-Algebra-Transistores.md'
  - 'Projetos/B-LogiComb.md'
  - 'Projetos/C-ula.md'
  #- 'Projetos/C-ula-dicas.md'
  - 'Projetos/D-LogSeq.md'
  - 'Projetos/E-CPU.md'
  #    - 'Projetos/E-CPU-Testando.md'
  - 'Projetos/F-Assembly.md'
  - 'Projetos/G-Assembler.md'
  - 'Projetos/H-VM.md'
  #- 'Projetos/I-VMtranslator.md'
  #- 'Projetos/X-MR.md'

- Labs:
  - 'Labs/Lab1-A-Transistores.md'
  - 'Lab 2: Github':
    - 'Labs/Lab2.1-Ambiente.md'
    - 'Labs/Lab2.2-Ambiente.md'
  - 'Labs/Lab3-LogiComb-FPGA.md'
  - 'Labs/Lab4-LogiComb.md'
  - 'Labs/Lab5-ULA.md'
  - 'Labs/Lab6-Waves.md'
  - 'Labs/Lab7-ULA.md'  
  - 'Labs/Lab8-Seq.md'
  - 'Labs/Lab9-PequenaCPU.md'
  - 'Labs/Lab10-CPU.md'
  - 'Labs/Lab11-Assembly.md'
  - 'Labs/Lab12-Assembly.md'
  - 'Labs/Lab13-Assembly.md'
  - 'Labs/Lab14-Assembly.md'
  - 'Labs/Lab15-Assembly-FPGA.md'
  - 'Lab 16: Assembler':
    - 'Labs/Lab16.1-Assembler.md'
    - 'Labs/Lab16.2-Assembler.md'
    - 'Labs/Lab16.3-Assembler.md'
    - 'Labs/Lab16.4-Assembler.md'
    - 'Labs/Lab16.5-Assembler.md'
    - 'Labs/Lab16.6-Assembler.md'
  - 'Labs/Lab17-VM.md'
  #- 'Lab 18: VMtranslator':
  #  - 'Labs/Lab18.1-VMtranslator.md'
  #  - 'Labs/Lab18.2-VMtranslator.md'

- 'Teoria':
  - 'commum-content/teoria/Teoria-Dados.md'
  - 'commum-content/teoria/Teoria-Aritmetica-Binaria.md'
  - 'commum-content/teoria/Teoria-Algebra-Booleana.md'
  - 'commum-content/teoria/Teoria-CMOS.md'
  - 'commum-content/teoria/Teoria-RTL.md'
  - 'commum-content/teoria/Teoria-Componentes.md'
  - 'commum-content/teoria/Teoria-Aritmetica-Binaria-HW.md'
  - 'commum-content/teoria/Teoria-ULA.md'
  - 'commum-content/teoria/Teoria-Logica-Sequencial.md'
  - 'commum-content/teoria/Teoria-Sequencial-Componentes.md'
  - 'commum-content/teoria/Teoria-Z01.md'
  - "commum-content/teoria/Teoria-Assembly.md"
  - 'commum-content/teoria/Teoria-Z01-mapadeMemoria.md'
  - 'commum-content/teoria/Teoria-nasm-jump.md'
  - 'commum-content/teoria/Teoria-Linguagem-de-Maquina.md'
  - 'commum-content/teoria/Teoria-Assembler.md'
  - 'commum-content/teoria/Teoria-Assembler-SymbolTable.md'
  - 'commum-content/teoria/Teoria-vm.md'
  - 'commum-content/teoria/Teoria-vm-segmentos.md'
  - 'commum-content/teoria/Teoria-vm-jump.md'
  - 'commum-content/teoria/Teoria-vm-funcoes.md'
  - 'commum-content/teoria/Teoria-vm-memoria.md'
  - 'Teoria/VMtranslator-memoria.md'
  - 'Vídeo Aulas (Luciano)': 'Util/Util-Video-Aulas.md'

- 'VHDL':
  - 'VHDL/VHDL-basico.md'
  - 'VHDL/VHDL-Combinacional.md'
  - 'VHDL/VHDL-port-map.md'
  - 'VHDL/VHDL-Sequencial.md'
  - 'VHDL/VHDL-RTL.md'
  - 'VHDL/VHDL-exemplos.md'

- 'Z01':
  - "Resumo Assembly": "commum-content/z01/z01-Resumo-Assembly.md"
  - "Z01.1 Cheat Sheet": "commum-content/z01/z01-Cheat-Sheet.md"
  - "Instruction Set": "commum-content/z01/z01-InstructionSet.md"
  - "Resumo VM": "commum-content/z01/z01-Resumo-VM.md"

- 'Estudo':
  - 'Dados Digitais - 1': 'https://docs.google.com/spreadsheets/d/1rN_zQqYaVI8PjAhKqEBCmY-_06I0X9dD0RddcI-miJs/edit?usp=sharing'
  - 'Dados Digitais - 1 - pdf': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1.pdf'
  - 'Dados Digitais - 1 - respostas': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1_respostas.pdf'
  - 'Exercicios/Exercicio-Dados-2.md'
  - 'Dados Digitais - 2 - respostas': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Exercicio-Dados-2_resolucao.pdf'
  - 'Exercicios/Exercicio-Algebra-Booleana-1.md'
  - 'Exercicios/Exercicio-Algebra-Booleana-2.md'  
  - 'Handout Aritmetica Booleana': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana.pdf'
#  - 'Handout Aritmetica Booleana - Resolução': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana_resolvido.pdf'
  - 'Lógica Sequencial': 'https://forms.gle/XMsFCDMYsmz1qUP86'
#  - 'Lógica Sequencial - resolução': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Lógica-Sequencial_resolucao.pdf'
  - 'Linguagem de Máquina': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Linguagem_de_maquina.pdf' #'https://forms.gle/6jNZR4CAELJ69ZjXA'
#  - 'Linguagem de Máquina - respostas': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Linguagem_de_maquina_respostas.pdf' 
  - 'Exercicios/Exercicio-CPU-1.md'
  - 'Exercicios/Exercicio-CPU-2.md'

- Útil:
  - "commum-content/util/Util-Comecando-novo-projeto.md"
  - "commum-content/util/Util-vixi-sou-scrum.md"
  - "commum-content/util/Util-vixi-sou-dev.md"
  - 'Util/Util-Dicas-Actions.md'
  - 'Dicas git': 'Util-Dicas-GIT.md'

- História:
  - 'Util/Historia-linux.md'


